name: Build 
on:
  workflow_dispatch:
jobs:
  buildwin:
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v2
    - name: Install and Build
      run:
        npm install && npm run build
    - name: Upload File
      uses: actions/upload-artifact@v2
      with:
        name: windows
        path: dist_electron/*exe
